name: Welcome New Contributors

on:
  pull_request:
    types: [opened]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the contributor
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: |
            👋 Hi there! Thanks for opening your first pull request!
            We appreciate your contribution. Please make sure to follow the contribution guidelines.
